Update workflow yml

diff --git a/.github/workflows/dotnet/pr_checks.yml b/.github/workflows/dotnet/pr_checks.yml
--- a/.github/workflows/dotnet/pr_checks.yml
+++ b/.github/workflows/dotnet/pr_checks.yml
@@ -1,62 +1,82 @@
-name: Build and Coverage
+## how to start the workflow?
+## create new .yml file and uncomment following the steps below
+## *input fields are not required*
+
+#name: Start workflow
+
+#on:
+  #push:
+  #  branches: ["main", "master", "stage", "dev", "release/*"]
+  #pull_request:
+  #  branches: ["main", "master", "stage", "dev", "release/*"]
+
+#jobs:
+  #run:
+    #uses: ./.github/workflows/workflow_run.yml
+    #with:
+      #coverage-threshold: 95
+      #dotnet-version: 7.0.x
+      #runs-on: ubuntu-latest
+
+name: Build, Test and Coverage
 
 on:
-  workflow_dispatch:
-  push:
-    branches: [ "main", "master", "stage", "dev", "release/*"]
-  pull_request:
-    branches: [ "main", "master", "stage", "dev", "release/*" ]
-    
-env:
-  DOTNET_VERSION: 7.0.x
-  COVERAGE_THRESHOLD: ${{vars.COVERAGE_THRESHOLD}}
-      
+  workflow_call:
+    inputs:
+      coverage-threshold:
+        description: "The minimum coverage threshold. Below this, the workflow will fail."
+        required: false
+        default: 90
+        type: string
+      dotnet-version:
+        description: "The version of dotnet to use."
+        required: false
+        default: 7.0.x
+        type: string
+      runs-on:
+        description: "Runner to use. Always try to use self-hosted runners."
+        required: false
+        default: ubuntu-latest
+        type: string
+        
 jobs:
-  build:
-    runs-on: ubuntu-latest
+  build_test_coverage:
+    name: Build, Test and Coverage
+    runs-on: ${{ inputs.runs-on }}
 
     steps:
-    - uses: actions/checkout@v3
-    
-    - name: Setup .NET
-      uses: actions/setup-dotnet@v3
-      with:
-        dotnet-version: ${{ env.DOTNET_VERSION }}
-        
-    - name: Restore dependencies
-      run: dotnet restore
-      
-    - name: Build
-      run: dotnet build --no-restore
+      - uses: actions/checkout@v4
 
-    - name: Format
-      run: dotnet format --verify-no-changes
-      
-    - name: Test
-      run: dotnet test -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover --no-build --verbosity normal test/TestProject1
-      
-    - name: Create test coverage badge
-      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
-      id: create_coverage_badge
-      with:
-        label: Unit Test Coverage
-        color: brightgreen
-        path: test/TestProject1/TestResults/coverage.opencover.xml
-        gist-filename: code-coverage.json
-        gist-id: 7f68482ee34cdce81dffbbdd6b88f5ac
-        gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}  
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v4
+        with:
+          dotnet-version: ${{ inputs.dotnet-version }}
 
-    - name: Report results to DeepSource
-      run: |
-       curl https://deepsource.io/cli | sh
-        ./bin/deepsource report --analyzer test-coverage --key csharp --value-file ./test/TestProject1/TestResults/coverage.opencover.xml
-      env:
-        DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
-        
-    - name: Coverage threshold
-      if: ${{ steps.create_coverage_badge.outputs.percentage < env.COVERAGE_THRESHOLD}}
-      run: |
-        echo "::error title="Coverage threshold"::Coverage is below threshold. Expected ${{env.COVERAGE_THRESHOLD}}%, got ${{steps.create_coverage_badge.outputs.percentage}}%"
-        exit 1
-        
-    
+      - name: Restore dependencies
+        run: dotnet restore
+
+      - name: Build
+        run: dotnet build --no-restore
+
+      - name: Format
+        run: dotnet format --verify-no-changes
+
+      - name: Test
+        run: dotnet test -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover --no-build --verbosity normal test/TestProject1
+
+      - name: Create test coverage badge
+        uses: simon-k/dotnet-code-coverage-badge@v1.0.0
+        id: create_coverage_badge
+        with:
+          label: Unit Test Coverage
+          color: brightgreen
+          path: test/TestProject1/TestResults/coverage.opencover.xml
+          gist-filename: code-coverage.json
+          gist-id: 7f68482ee34cdce81dffbbdd6b88f5ac
+          gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}
+
+      - name: Coverage threshold
+        if: ${{ steps.create_coverage_badge.outputs.percentage < inputs.coverage-threshold }}
+        run: |
+          echo "::error title="Coverage threshold"::Coverage is below threshold. Expected ${{ inputs.coverage-threshold }}%, got ${{ steps.create_coverage_badge.outputs.percentage }}%"
+          exit 1
